services:
  mysql:
    image: mariadb:10.6.4-focal
    container_name: coffee_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coffee_db
      MYSQL_USER: coffee_user
      MYSQL_PASSWORD: coffee_pass
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: coffee_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coffee_db
      SPRING_DATASOURCE_USERNAME: coffee_user
      SPRING_DATASOURCE_PASSWORD: coffee_pass

volumes:
  mysql_data: